  # PyPy versions
#  - "pypy2.7"
#  - "pypy3.5"
# command to install dependencies
#install:
#  - pip install .
#  - pip install -r requirements.txt
# command to run tests
#script: pytest

language: python
python:
  - "3.6"
script:
  - pytest
  - 'coverage run --source=. setup.py test'
  #- 'coverage run -m pytest'

after_success:
    coveralls
